export const FETCH_CATALOG_CATEGORIES_REQUEST = 'FETCH_CATALOG_CATEGORIES_REQUEST';
export const FETCH_CATALOG_CATEGORIES_CHANGE = 'FETCH_CATALOG_CATEGORIES_CHANGE';
export const FETCH_CATALOG_CATEGORIES_SUCCESS = 'FETCH_CATALOG_CATEGORIES_SUCCESS';
export const FETCH_CATALOG_ITEMS_REQUEST = 'FETCH_CATALOG_ITEMS_REQUEST';
export const FETCH_CATALOG_ITEMS_MORE = 'FETCH_CATALOG_ITEMS_MORE';
export const FETCH_CATALOG_ITEMS_SUCCESS = 'FETCH_CATALOG_ITEMS_SUCCESS';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';

export const SEARCH_CHANGE = 'SEARCH_CHANGE';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';