export const FETCH_TOP_SALES_CLEAR = 'FETCH_TOP_SALES_CLEAR';
export const FETCH_TOP_SALES_REQUEST = 'FETCH_TOP_SALES_REQUEST';
export const FETCH_TOP_SALES_FAILURE = 'FETCH_TOP_SALES_FAILURE';
export const FETCH_TOP_SALES_SUCCESS = 'FETCH_TOP_SALES_SUCCESS';